### ISSUE TITLE
Support for haskell node

### ISSUE THREAD

**Issue by Kidist-Abraham** [cardanians/adapools.org#1]
@cardanians 
Hello, our team used the adapools API to get the blacklisted pools on the ITN. I want to know if you guys are going to support the endpoints for black-listed and ambassador pools for the Haskell node?

**Comment by cardanians** [comment]
Hey, sure some endpoints are planned! 

For early stage now, check out fresh pool-list https://js.adapools.org/pools.json - as you see there is preparation for some - "stamp_amba" etc., but these "stamps" are for now null.

I believe, blacklist is not required in haskell-node, we have now only self-community strikes if someone tries to imitate a pool ticker :)

**Comment by Kidist-Abraham** [comment]
Thanks! Looking forward to it.
