### ISSUE TITLE
Pool fee information can be misleading

### ISSUE THREAD

**Issue by hodlonaut** [cardanians/adapools.org#4]
Steps to reproduce the issue:

1. Register stake pool with 0% variable fee
2. Wait for pool to appear in Adapools website/Yoroi wallet
3. Near the end of the epoch modify the pool and change variable fee to 50% - a little while later Adapools / Yoroi will show pool fee as 50% (fixed fee can also be hiked up to some ridiculous value as a part of this exercise)
4. Wait for epoch boundary and snapshot, then half an hour into new epoch modify the pool and change variable fee to 0% - a little while later Adapools / Yoroi will show pool fee as 0%.
5. Rinse and repeat steps 3 and 4 as much as you like

So while Adapools/Yoroi will continue showing the fee as 0% for almost entirety of the existence of the above-described pool, in fact the snapshots of the pool state will be capturing 50% variable fee and soon enough delegators to this pool will start seeing drastically reduced rewards than they expected when they saw a shiny highly ranked 0% pool in the pool list.

Correct behaviour would be to show the snapshotted fee value from the last epoch boundary - currently a couple of the community tools/explorers are doing something along these lines (pooltool.io, cardanoscan.io). Showing scheduled-but-not-in-effect fee value is incorrectly lulling delegators into a false sense of security in the above scenario. The solution can also be combined with showing pending-but-not-in-effect-yet fee as well potentially (definitely on adapools pool page, if there's room for it possibly in Yoroi)

Obviously while addressing the above, would be a good time to double check that whatever use current pool rankings make of the fee structure to make sure it uses the in-effect values, not queued-for-being-active-in-the-next-epoch-unless-someone-does-a-last-minute-hike...

**Comment by cardanians** [comment]
should be fixed

**Comment by hodlonaut** [comment]
Thanks for the prompt action, I will kick some tires on this fix over the next few days.
