### ISSUE TITLE
GENS3 not showing up and GENS4 showing incorrect metadata

### ISSUE THREAD

**Issue by Vardominator** [cardanians/adapools.org#5]
The following pool IDs are problematic on adapools.org:

GENS3: 126f84b8f88fd0f65de921ef521f2aa637e5e465cea06042c103fe22
* Not showing up at all

GENS4: 40efc97d08315ff9be5898f24af5b8b120669b43027662c3499dd785
* Not showing icon from extended metadata

These pools are showing a healthy state on pool.pm, pool.vet and pooltool.io, but not on Adapools or Yoroi. Can anyone on the Adapools team help?

**Comment by cardanians** [comment]
do not use tinyurl.

they are banning sometimes fetching.

**Comment by Vardominator** [comment]
@cardanians  do you recommend using git.io instead?

**Comment by cardanians** [comment]
I can't guarantee, but I don't know of anyone complaining about gitio :-) 

In both cases I recommend try that, because daedalus users could have problems same as have we.

Dont forgot after reregistering it could take ~4 hours to update.

**Comment by Vardominator** [comment]
@cardanians We re-registered with git.io and not seeing any immediate changes. Is ~4 hours typical? Any way we can check earlier?

**Comment by Vardominator** [comment]
@cardanians it has been 4 hours and we're still not seeing any changes. Any ideas on what we can try? This is starting to concern us quite a bit

**Comment by cardanians** [comment]
Im looking on this now and looks okay, please check.

**Comment by Vardominator** [comment]
@cardanians Thank you so much for your help!!!
Any idea why the icon is not showing up for GENS4? https://adapools.org/pool/40efc97d08315ff9be5898f24af5b8b120669b43027662c3499dd785

**Comment by MarvinBertin** [comment]
GENS3 works now but GENS4 logo is still not showing up. The unreliability is a bit worrisome to say the least.

**Comment by cardanians** [comment]
probably only caching issue (time will solve that)
