### ISSUE TITLE
GENS5 scam pool

### ISSUE THREAD

**Issue by Vardominator** [cardanians/adapools.org#6]
Someone has created a scam pool with the ticker [`GENS5`](https://adapools.org/pool/c485ab20bd3f105e59f3c50a0d3fbaf615a51f70a1c6d29d00a1fd27). This is clearly being used to trick the community into staking with a pool that has nothing to do with Genius Yield. Since Genius Yield already operates GENS1, GENS2, GENS3 and GENS4, people might be easily tricked into staking with GENS5. Would it be possible to report this pool in any way and potentially have it hidden on adapools?

**Comment by cardanians** [comment]
done!
in future please better way is send mail as is described here: https://adapools.org/ticker-disputes
