### ISSUE TITLE
Pool ticker BDRK not showing updated info

### ISSUE THREAD

**Issue by spowser** [cardanians/adapools.org#7]
PoolId: b046bd7ea0e09f16dc063c9ca5402d930346da176ce74d799fc98169

Currently has the wrong ticker (WIFE) and is showing as retired.  Many of the details don't seem to be updating from what is stored onchain

**Comment by spowser** [comment]
Just checked and things seem to be looking much better.  Active Stake seems wrong since it's below the Pledge but I'll wait a few more epochs to see if that gets sorted out

**Comment by cardanians** [comment]
Yeah, thats "correct" as we ignored pool data while retire/post-retire. Understand, this is not ideal solution. But will be solved with incoming adapoolsV2. Next epoch you should see correct number.

**Comment by spowser** [comment]
This is resolved
